# Generated by Django 4.2.20 on 2025-04-07 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_playerprofile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_file', models.FileField(upload_to='videos/', verbose_name='Video File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('player_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='players.playerprofile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
