# Generated by Django 4.2.20 on 2025-04-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='allow_comments',
            field=models.BooleanField(default=True, help_text='Check this box to allow users to comment on this video.', verbose_name='Allow Comments'),
        ),
    ]
