# Generated by Django 4.2.20 on 2025-04-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_videoupload_allow_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Optional: Provide an email address if you wish to be contacted by verified scouts.', max_length=254, null=True, verbose_name='Contact Email (for scouts)'),
        ),
    ]
