# Generated by Django 4.2.20 on 2025-04-22 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_playerprofile_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_name', models.CharField(max_length=100, verbose_name='Statistic Name')),
                ('stat_value', models.CharField(max_length=50, verbose_name='Value')),
                ('stat_unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unit')),
                ('date_recorded', models.DateField(verbose_name='Date Recorded')),
                ('player_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='players.playerprofile')),
            ],
            options={
                'ordering': ['stat_name', '-date_recorded'],
            },
        ),
    ]
