# Generated by Django 4.2.20 on 2025-04-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_playerstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='primary_sport',
            field=models.CharField(choices=[('Soccer', 'Soccer'), ('Cricket', 'Cricket'), ('Rugby', 'Rugby'), ('Other', 'Other/Unspecified')], default='Other', help_text='Select the main sport you play.', max_length=50, verbose_name='Primary Sport'),
        ),
    ]
