# Generated by Django 4.2.20 on 2025-04-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_cricketmatchstat_match_physicalstat_rugbymatchstat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='physicalstat',
            options={'ordering': ['-date_recorded', 'stat_name'], 'verbose_name': 'Physical Stat', 'verbose_name_plural': 'Physical Stats'},
        ),
        migrations.RemoveField(
            model_name='physicalstat',
            name='category',
        ),
        migrations.AlterField(
            model_name='physicalstat',
            name='stat_name',
            field=models.CharField(choices=[('Height', 'Height'), ('Weight', 'Weight'), ('Wingspan', 'Wingspan'), ('Hand Size', 'Hand Size'), ('50m Sprint', '50m Sprint'), ('100m Sprint', '100m Sprint'), ('40-Yard Dash', '40-Yard Dash'), ('10-Yard Split', '10-Yard Split'), ('Pro Agility Shuttle', 'Pro Agility Shuttle (5-10-5)'), ('3-Cone Drill', '3-Cone Drill (L-Drill)'), ('Vertical Jump', 'Vertical Jump'), ('Broad Jump', 'Broad Jump'), ('Beep Test Level', 'Beep Test Level'), ('Yo-Yo Test Level', 'Yo-Yo Intermittent Test Level'), ('Other', 'Other Test/Measurement')], help_text='Select the standard test or measurement.', max_length=50, verbose_name='Statistic Name'),
        ),
        migrations.AlterField(
            model_name='physicalstat',
            name='stat_unit',
            field=models.CharField(blank=True, choices=[('cm', 'cm'), ('m', 'm'), ('inches', 'inches'), ('feet', 'feet'), ('yards', 'yards'), ('kg', 'kg'), ('lbs', 'lbs'), ('stone', 'stone'), ('seconds', 'seconds'), ('minutes', 'minutes'), ('level', 'level'), ('reps', 'reps'), ('%', '%'), ('N/A', 'N/A'), ('Other', 'Other')], help_text='Select the appropriate unit.', max_length=20, null=True, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='physicalstat',
            name='stat_value',
            field=models.CharField(help_text='Enter the measurement value (e.g., 185, 6\'1", 4.52, 11.2).', max_length=50, verbose_name='Value'),
        ),
    ]
