# Generated by Django 4.2.20 on 2025-04-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_alter_physicalstat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mark this video to feature it prominently (Admin only).', verbose_name='Admin Featured'),
        ),
        migrations.AddField(
            model_name='videoupload',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the video has been viewed.', verbose_name='View Count'),
        ),
    ]
