# Generated by Django 4.2.20 on 2025-04-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_videoupload_is_featured_videoupload_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoupload',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Optional: Upload a representative image for the video (e.g., JPG, PNG).', null=True, upload_to='videos/thumbnails/', verbose_name='Thumbnail Image'),
        ),
    ]
