# Generated by Django 4.2.20 on 2025-04-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_videoupload_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='city',
            field=models.CharField(blank=True, help_text='Your current city or town.', max_length=100, null=True, verbose_name='City / Town'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='country',
            field=models.CharField(blank=True, help_text='The country you are based in.', max_length=100, null=True, verbose_name='Country'),
        ),
    ]
