# Generated by Django 4.2.20 on 2025-04-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0015_subscription_profileview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cricketmatchstat',
            name='match_format_override',
        ),
        migrations.AddField(
            model_name='physicalstat',
            name='stat_value_numeric',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Numerical value for ranking/comparison (e.g., 185 for cm, 4.52 for seconds, 0.85 for m).', max_digits=10, null=True, verbose_name='Value (Numeric)'),
        ),
        migrations.AlterField(
            model_name='physicalstat',
            name='stat_value',
            field=models.CharField(help_text='Enter the measurement value (e.g., 185, 6\'1", 4.52, 11.2).', max_length=50, verbose_name='Value (as text)'),
        ),
    ]
